### ISSUE TITLE
Broken characters on completions page

### ISSUE THREAD

**Issue by jish** [sublimetext-io/docs.sublimetext.io#64] opened 2022-08-28 15:39 UTC
### Steps to reproduce

1. In Firefox `104.0`
2. Navigate to https://docs.sublimetext.io/guide/extensibility/completions.html#how-to-use-completions

### Actual behavior:

Characters render incorrectly, leaving the reader confused.

<img width="812" alt="Screen Shot 2022-08-28 at 8 28 36 AM" src="https://user-images.githubusercontent.com/1817/187082126-203917d5-d224-409c-a36a-ad773168da85.png">

### Expected behavior:

1. The characters should display properly
2. When characters fail to display the content should still be readable

> Completions can be inserted in two ways:
> * Through the completions list. Note: the completions list can be activated by pressing control and spacebar (Ctrl ␣), or
> * by pressing the **foo key (`f`)**.

**Comment by jish** [comment] 2022-08-28 17:59
Same behavior in Safari version `15.3`:

<img width="982" alt="Screen Shot 2022-08-28 at 10 57 09 AM" src="https://user-images.githubusercontent.com/1817/187088098-a5f21e8e-7da3-462f-a4de-594fca8e4df4.png">

Characters are missing, making the tutorial unclear.

**Comment by FichteFoll** [comment] 2022-08-29 07:47
I assume your FireFox is also running on macOS?

**Comment by jish** [comment] 2022-08-31 03:37
Yes, that is correct.

Both Mac OS (`12.2.1`) and iOS (`15.6.1`), both Firefox and Safari

**Comment by FichteFoll** [comment] 2023-10-29 18:58
Closing as a duplicate of #20.

**Closed by FichteFoll** 2023-10-29 18:58 UTC
Labels: bug
